version: 2.1
jobs:
  test:
    docker:
      - image: cimg/ruby:3.1
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: bundle install
      - run:
          name: Setup environmental valuables
          command: |
            echo "API_KEY=$SENDGRID_API_KEY" >> .env
            echo "TOS=alice@sink.sendgrid.net,bob@sink.sendgrid.net,carol@sink.sendgrid.net" >> .env
            echo "FROM=you@example.com" >> .env
      - run:
          name: Show versions
          command: |
            ruby --version
            cat Gemfile.lock
      - run:
          name: Test
          command: ruby sendgridjp-ruby-example-test.rb
workflows:
  version: 2
  normal_deploy_workflow:
    jobs:
      - test
  monthly_workflow:
    triggers:
      - schedule:
          cron: "0 0 2 * *"
          filters:
            branches:
              only:
                - main
    jobs:
      - test